### ISSUE TITLE
docs: Mention installation process for a Symfony app

### ISSUE THREAD

**Issue by AlexeyKosov** [stecman/symfony-console-completion#76]
I think it's worth to mention in the docs that in order to install it in a Symfony app, the "_completion" command should be registered in the config file rather than added to the `getDefaultCommands`:

app/config/services.yml:
```
    console.completion_command:
        class: Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand
        tags:
            -  { name: console.command }
```
